MVC_Project/Models/ExCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Project.Models
{
    [Table("tbl_Category")]
    public class ExCategory
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name Must be Entered")]
        public String Name { get; set; }

        [Required(ErrorMessage = "Expense Limit Must be Entered")]
        public long Ex_Limit { get; set; }
    }
}

MVC_Project/Controllers/ExCategoryController.cs
using MVC_Project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Project.Controllers
{
    public class ExCategoryController : Controller
    {
        DatabaseConnection Db_Conn = new DatabaseConnection();
        // GET: ExCategory
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(ExCategory e)
        {
            decimal cat_sum = Db_Conn.Model_Category.ToList().Sum(h => h.Ex_Limit);
            totalLimit tl = Db_Conn.Model_totalLimit.FirstOrDefault(h => h.Id == 1);

            cat_sum = cat_sum + e.Ex_Limit;

            if (cat_sum > tl.Total_Limit)
            {
                TempData["Alertd"] = "Increase Your total Limit !!";
                return RedirectToAction("ListLimit");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    ExCategory e1 = new ExCategory();
                    // e1.Name = "Harsh";
                    //e1.Ex_Limit = 2;
                    e1.Name = e.Name;
                    e1.Ex_Limit = e.Ex_Limit;

                    Db_Conn.Model_Category.Add(e1);
                    TempData["AlertMsg"] = "New Category Inserted...";
                    Db_Conn.SaveChanges();
                    return RedirectToAction("ListCategory");
                }
                ModelState.Clear();
            }
            return View("Create");
        }

        public ActionResult ListCategory()
        {

            decimal cat_sum = Db_Conn.Model_Category.ToList().Sum(h => h.Ex_Limit);
            totalLimit tl = Db_Conn.Model_totalLimit.FirstOrDefault(h => h.Id == 1);

            decimal remain = tl.Total_Limit - cat_sum;
            TempData["Remain"] = remain;

            var list = Db_Conn.Model_Category.ToList();
            Db_Conn.SaveChanges();

            return View(list);
        }

        public ActionResult Delete(int id)
        {
            var del = Db_Conn.Model_Category.Where(h => h.Id == id).First();
            Db_Conn.Model_Category.Remove(del);
            Db_Conn.SaveChanges();
            TempData["AlertMsg"] = "Record Deleted...";

            return RedirectToAction("ListCategory");

            //var list = Db_Conn.Model_Category.ToList();
            //Db_Conn.SaveChanges();

            return View("Create");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var row = Db_Conn.Model_Category.Where(h => h.Id == id).FirstOrDefault();
            return View(row);
        }

        [HttpPost]
        public ActionResult EditCategory(ExCategory e)
        {
            ExCategory e1 = new ExCategory();
            if (ModelState.IsValid)
            {
                e1.Id = e.Id;
                e1.Name = e.Name;
                e1.Ex_Limit = e.Ex_Limit;

                Db_Conn.Entry(e1).State = EntityState.Modified;
                Db_Conn.SaveChanges();
                TempData["AlertMsg"] = "Record Updated Successful...";

                return RedirectToAction("ListCategory");
            }
            ModelState.Clear();
            return View("Create");
            // var row = Db_Conn.Model_Category.Where(h => h.Id == id).FirstOrDefault();
        }


        //--------Expense Action--------------

        public ActionResult CreateExp()
        {
            var delist = Db_Conn.Model_Category.ToList();
            ViewBag.Id = new SelectList(delist, "Id", "Name");

            return View();
        }

        [HttpPost]
        public ActionResult AddExpense(Expense ex)
        {
            Expense e_obj = new Expense();

            decimal total_exp = Db_Conn.Model_Expense.Where(h => h.Id == ex.Id).ToList().Sum(h => h.Amount);
            ExCategory exCat = Db_Conn.Model_Category.FirstOrDefault(h => h.Id == ex.Id);

            total_exp = total_exp + ex.Amount;

            if (total_exp > exCat.Ex_Limit)
            {
                TempData["Alertd"] = "Please First Increase Category Exp_Limit...";
                return RedirectToAction("ListCategory");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var delist = Db_Conn.Model_Category.ToList();
                    ViewBag.Id = new SelectList(delist, "Id", "Name");

                    e_obj.Title = ex.Title;
                    e_obj.Description = ex.Description;
                    e_obj.Amount = ex.Amount;
                    e_obj.Id = ex.Id;
                    e_obj.Date = DateTime.Now;

                    Db_Conn.Model_Expense.Add(e_obj);
                    TempData["AlertMsg"] = "New Category Inserted...";
                    Db_Conn.SaveChanges();
                    return RedirectToAction("ListExpense");
                }
                ModelState.Clear();
            }

            return View("CreateExp");
        }

        public ActionResult ListExpense()
        {
            //var delist = Db_Conn.Model_Category.ToList();
            //ViewBag.Id = new SelectList(delist, "Id", "Name");

            //var list = Db_Conn.Model_Expense.ToList();
            //Db_Conn.SaveChanges();

            List<Expense> exp = Db_Conn.Model_Expense.ToList();
            List<ExCategory> excat = Db_Conn.Model_Category.ToList();

            var list = from e in exp
                       join d in excat on e.Id equals d.Id into Table1
                       from d in Table1.ToList()
                       select new ViewModel
                       {
                           expense = e,
                           exCategory = d
                       };

            return View(list);
        }





        public ActionResult CatNameSearch(int id)
        {
            //var delist = Db_Conn.Model_Category.ToList();
            //ViewBag.Id = new SelectList(delist, "Id", "Name");

            //var list = Db_Conn.Model_Expense.Where(h=>h.Id == id).ToList();
            //Db_Conn.SaveChanges();

            decimal cat_sum = Db_Conn.Model_Expense.Where(h => h.Id == id).ToList().Sum(h=>h.Amount);
            ExCategory explimit = Db_Conn.Model_Category.FirstOrDefault(h=>h.Id == id);

            decimal remian = explimit.Ex_Limit - cat_sum;
            TempData["Remain"] = remian;

            List<Expense> exp = Db_Conn.Model_Expense.ToList();
            List<ExCategory> excat = Db_Conn.Model_Category.ToList();



            var list = from e in exp
                       join d in excat on e.Id equals d.Id into Table1
                       from d in Table1.Where(h => h.Id == id).ToList()
                       select new ViewModel
                       {
                           expense = e,
                           exCategory = d
                       };

            //ViewBag.totalrow = Db_Conn.Model_Category.Count();


            return View(list);
        }



        public ActionResult DeleteEx(int exp_id)
        {
            var del = Db_Conn.Model_Expense.Where(h => h.Exp_Id == exp_id).First();
            Db_Conn.Model_Expense.Remove(del);
            Db_Conn.SaveChanges();
            TempData["AlertMsg"] = "Record Deleted...";
            return RedirectToAction("ListExpense");

            return View("CreateExp");
        }

        [HttpGet]
        public ActionResult EditExpense(int exp_id)
        {
            var delist = Db_Conn.Model_Category.ToList();
            ViewBag.Id = new SelectList(delist, "Id", "Name");


            var row = Db_Conn.Model_Expense.Where(h => h.Exp_Id == exp_id).FirstOrDefault();
            return View(row);
        }

        [HttpPost]
        public ActionResult EditExpense(Expense ex)
        {
            var delist = Db_Conn.Model_Category.ToList();
            ViewBag.Id = new SelectList(delist, "Id", "Name");

            Expense e1 = new Expense();
            if (ModelState.IsValid)
            {
                e1.Exp_Id = ex.Exp_Id;
                e1.Title = ex.Title;
                e1.Description = ex.Description;
                e1.Amount = ex.Amount;
                e1.Id = ex.Id;
                e1.Date = DateTime.Now;

                Db_Conn.Entry(e1).State = EntityState.Modified;
                Db_Conn.SaveChanges();
                TempData["AlertMsg"] = "Record Updated Successful...";

                return RedirectToAction("ListExpense");
            }
            ModelState.Clear();

            return View();
        }

        //---------

        public ActionResult CreateLimit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddLimit(totalLimit tl)
        {
            if (ModelState.IsValid)
            {
                totalLimit t = new totalLimit();

                t.Total_Limit = tl.Total_Limit;

                Db_Conn.Model_totalLimit.Add(t);
                TempData["AlertMsg"] = "Total Expense Limit Created...";
                Db_Conn.SaveChanges();
                return RedirectToAction("ListLimit");
            }

            return View("CreateLimit");
        }

        public ActionResult ListLimit()
        {
            var list = Db_Conn.Model_totalLimit.Where(h => h.Id == 1).ToList();
            Db_Conn.SaveChanges();

            return View(list);
        }

        [HttpGet]
        public ActionResult EditLimit(int id)
        {
            var row = Db_Conn.Model_totalLimit.Where(h => h.Id == id).FirstOrDefault();
            return View(row);
        }

        [HttpPost]
        public ActionResult EditLimit(totalLimit tl)
        {
            totalLimit t1 = new totalLimit();
            if (ModelState.IsValid)
            {
                t1.Id = tl.Id;
                t1.Total_Limit = tl.Total_Limit;


                Db_Conn.Entry(t1).State = EntityState.Modified;
                Db_Conn.SaveChanges();

MVC_Project/Views/ExCategory/CatNameSearch.cshtml
@model IEnumerable<MVC_Project.Models.ViewModel>

@{
    ViewBag.Title = "CatNameSearch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/main.js"></script>
<script src="~/Scripts/Fontawsome.js"></script>

<h2>Filter Record</h2>

@if (TempData["AlertMsg"] != null)
{
    <div class="alert alert-success">
        <strong>Success !&#9989;</strong>@TempData["AlertMsg"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

<table class="table table-hover">
    <tr class="text-capitalize bg-dark text-white text-center">
        <th>Title</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Category Name</th>
        <th>Date</th>
        <th>Expense Limit</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>@item.expense.Title</td>
            <td>@item.expense.Description</td>
            <td>@item.expense.Amount</td>
            <td>@item.exCategory.Name</td>
            <td>@item.expense.Date</td>
            <td>@item.exCategory.Ex_Limit</td>
            <td>
                <a href="@Url.Action("EditExpense", new { item.expense.Exp_Id, item.expense.Title, item.expense.Description, item.expense.Amount, item.exCategory.Name, item.expense.Date })" class="btn btn-success"><i class="fas">&#xf044; Edit</i></a>
                <a href="@Url.Action("DeleteEx", new { @item.expense.Exp_Id })" class="btn btn-danger"><i class='fas'>&#xf2ed; Delete</i></a>
            </td>
        </tr>
    }
</table>

<div>&nbsp;</div>

<div class="container">
    <div class="row">
        <div class="col-sm-5 col-md-5 col-xl-5 col-lg-5">
            <table class="table table-bordered">
                <tr class="text-capitalize bg-dark text-white text-center">
                    <th>Total Amount Is :</th>
                </tr>
                <tr class="text-center">
                    <td>@Model.Sum(h => h.expense.Amount)</td>
                </tr>
            </table>
        </div>

        <div class="col-sm-1 col-md-1 col-xl-1 col-lg-1">

        </div>

        <div class="col-sm-5 col-md-5 col-xl-5 col-lg-5">
            @if (TempData["Remain"] != null)
            {
                <table class="table table-bordered">
                    <tr class="text-capitalize bg-dark text-white text-center">
                        <th>Remain Amount Is :</th>
                    </tr>
                    <tr class="text-center">
                        <td>@TempData["Remain"]</td>
                    </tr>
                </table>
            }
        </div>
    </div>
</div>

MVC_Project/Views/ExCategory/Create.cshtml
@model MVC_Project.Models.ExCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .error {
        color: red;
    }
</style>

<h2>Create Category</h2>

@using (Html.BeginForm("AddCategory", "ExCategory", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            <label>Name</label>
            @Html.ValidationMessageFor(h => h.Name, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Name, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Expanse_Limit</label>
            @Html.ValidationMessageFor(h => h.Ex_Limit, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Ex_Limit, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
}

MVC_Project/Views/ExCategory/CreateExp.cshtml
@model MVC_Project.Models.Expense
@{
    ViewBag.Title = "CreateExp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/main.js"></script>
@if (TempData["AlertMsg"] != null)
{
    <div class="alert alert-success">
        <strong>Success !!&#9989;</strong>@TempData["AlertMsg"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}


<style>
    .error {
        color: red;
    }
</style>

<h2>Create-Expense</h2>

@using (Html.BeginForm("AddExpense", "ExCategory", FormMethod.Post))
{
    <div class="container">

        <div class="form-group">
            <label>Title</label>
            @Html.ValidationMessageFor(h => h.Title, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Title, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Description</label>
            @Html.ValidationMessageFor(h => h.Description, "", new { @class = "error" })
            @Html.TextAreaFor(h => h.Description, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Amount</label>
            @Html.ValidationMessageFor(h => h.Amount, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Amount, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Category Name</label>
            @Html.ValidationMessageFor(h => h.Id, "", new { @class = "error" })
            @Html.DropDownList("Id", null, new { @class = "form-control" })
        </div>

        <div class="form-grou" style="display:none;">
            <label>Date Time</label>
            @*@Html.TextBoxFor(h=>h.Date,new { @class="form-control" })*@
            @*@Html.TextBoxFor(h=>h.Date,new { @class="form-control" })*@
            @Html.TextBox("Date", DateTime.Now, new { @disabled = "disabled", @class = "form-control" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>

    </div>
}

MVC_Project/Views/ExCategory/CreateLimit.cshtml
@model MVC_Project.Models.totalLimit

@{
    ViewBag.Title = "CreateLimit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create-Limit</h2>

<style>
    .error {
        color: red;
    }
</style>


@using (Html.BeginForm("AddLimit", "ExCategory", FormMethod.Post))
{
    <div class="container">


        <div class="form-group">
            <label>Total Limit</label>
            @Html.ValidationMessageFor(h => h.Total_Limit, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Total_Limit, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
}

MVC_Project/Views/ExCategory/Dashboard.cshtml
@using MVC_Project.Models;
@model MultiViewModel

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Dashboard</h2>

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-lg-9 col-md-9 col-xl-9">
            <table class="table table-bordered">
                <tr class="text-capitalize bg-dark text-white text-center">
                    <th>Title</th>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>CategoryName</th>
                    <th>Date</th>
                    @*<th>Action</th>*@
                </tr>

                @foreach (var item in Model.Expenses)
                {
                    <tr class="text-center">
                        <td>@item.Title</td>
                        <td>@item.Description</td>
                        <td>@item.Amount</td>
                        <td>@item.Id</td>
                        <td>@item.Date</td>
                        @*<td>
                                <a href="@Url.Action("EditExpense", new { item.Exp_Id, item.Title, item.Description, item.Amount,item.Id,item.Date })" class="btn btn-success">Edit</a>
                                <a href="@Url.Action("DeleteEx", new { @item.Exp_Id })" class="btn btn-danger">Delete</a>
                            </td>*@
                    </tr>
                }
            </table>
        </div>
        <div class="col-sm-3 col-lg-3 col-md-3 col-xl-3">
            <table class="table table-bordered">
                <tr class="text-capitalize bg-dark text-white text-center">
                    <th>CategoryId</th>
                    <th>ExpanseLimit</th>
                    @*<th>Action</th>*@
                </tr>

                @foreach (var item in Model.exCategories)
                {
                    <tr class="text-center">
                        <td>@item.Name</td>
                        <td>@item.Ex_Limit</td>
                        @*<td>
                                <a href="@Url.Action("EditCategory",new { item.Id,item.Name,item.Ex_Limit })" class="btn btn-success">Edit</a>
                                <a href="@Url.Action("Delete",new { item.Id})" class="btn btn-danger">Delete</a>
                            </td>*@
                    </tr>
                }
            </table>
        </div>
    </div>

    <div>&nbsp;</div>

    <div class="row">
        <div class="col-sm-5 col-lg-5 col-md-5 col-xl-5">
            <table class="table table-bordered">
                <tr class="text-capitalize bg-dark text-white text-center">
                    <th>Total Expense Amount Is :</th>
                    @*<th>Action</th>*@
                </tr>


                <tr class="text-center">
                    <td><strong>@ViewBag.Exp</strong></td>
                    @*<td>
                        <a href="@Url.Action("EditLimit",new { item.Id,item.Total_Limit })" class="btn btn-success">Edit</a>
                    </td>*@
                </tr>
            </table>
        </div>

        <div class="col-sm-1 col-md-1"></div>

        <div class="col-sm-5 col-lg-5 col-md-5 col-xl-5">
            <table class="table table-bordered">
                <tr class="text-capitalize bg-dark text-white text-center">
                    <th>TotalLimit</th>
                    @*<th>Action</th>*@
                </tr>

                @foreach (var item in Model.totalLimits)
                {
                    <tr class="text-center">
                        <td>@item.Total_Limit</td>
                        @*<td>
                            <a href="@Url.Action("EditLimit",new { item.Id,item.Total_Limit })" class="btn btn-success">Edit</a>
                        </td>*@
                    </tr>
                }
            </table>

        </div>
    </div>
</div>

MVC_Project/Views/ExCategory/EditCategory.cshtml
@model MVC_Project.Models.ExCategory

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .error {
        color: red;
    }
</style>

<h2>Edit-Category</h2>

@using (Html.BeginForm("EditCategory", "ExCategory", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @Html.HiddenFor(h => h.Id)
            <label>Name</label>
            @Html.ValidationMessageFor(h => h.Name, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Name, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Expanse_Limit</label>
            @Html.ValidationMessageFor(h => h.Ex_Limit, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Ex_Limit, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
}

MVC_Project/Views/ExCategory/EditExpense.cshtml
@model MVC_Project.Models.Expense

@{
    ViewBag.Title = "EditExpense";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit-Expense</h2>

<style>
    .error {
        color: red;
    }
</style>

@using (Html.BeginForm("EditExpense", "ExCategory", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @Html.HiddenFor(h => h.Exp_Id)
            <label>Title</label>
            @Html.ValidationMessageFor(h => h.Title, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Title, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Description</label>
            @Html.ValidationMessageFor(h => h.Description, "", new { @class = "error" })
            @Html.TextAreaFor(h => h.Description, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Amount</label>
            @Html.ValidationMessageFor(h => h.Amount, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Amount, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Category Name</label>
            @*@Html.ValidationMessageFor(h => h.Id, "", new { @class = "error" })*@
            @Html.DropDownList("Id", null, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label>Date Time</label>
            @*@Html.TextBoxFor(h=>h.Date,new { @class="form-control" })*@
            @*@Html.TextBoxFor(h=>h.Date,new { @class="form-control" })*@
            @Html.TextBox("Date", DateTime.Now, new { @disabled = "disabled", @class = "form-control redable" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>

    </div>
}

MVC_Project/Views/ExCategory/EditLimit.cshtml
@model MVC_Project.Models.totalLimit
@{
    ViewBag.Title = "EditLimit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .error {
        color: red;
    }
</style>


<h2>Edit-Limit</h2>

@using (Html.BeginForm("EditLimit", "ExCategory", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @Html.HiddenFor(h => h.Id)
            <label>Total Limit</label>
            @Html.ValidationMessageFor(h => h.Total_Limit, "", new { @class = "error" })
            @Html.TextBoxFor(h => h.Total_Limit, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </div>
}

MVC_Project/Views/ExCategory/ListCategory.cshtml
@model List<MVC_Project.Models.ExCategory>

@{
    ViewBag.Title = "ListCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<script src="~/Scripts/main.js"></script>
<script src="~/Scripts/Fontawsome.js"></script>

<h2>Show Category</h2>
@if (TempData["AlertMsg"] != null)
{
    <div class="alert alert-success">
        <strong>Success !&#9989;</strong>@TempData["AlertMsg"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

@if (TempData["Alertd"] != null)
{
    <div class="alert alert-danger">
        <i style='font-size:24px' class='fas'>&#xf071;</i>@TempData["Alertd"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}
<table class="table table-bordered">
    <tr class="text-capitalize bg-dark text-white text-center">
        <th>Category Name</th>
        <th>Expanse Limit</th>
        <th>Action</th>
    </tr>
    
    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>@Html.ActionLink(item.Name, "CatNameSearch", "ExCategory", new { Id = item.Id }, null)</td>
            <td>@item.Ex_Limit</td>
            <td>
                <a href="@Url.Action("EditCategory",new { item.Id,item.Name,item.Ex_Limit })" class="btn btn-success"><i class="fas">&#xf044; Edit</i></a>
                <a href="@Url.Action("Delete",new { item.Id})" class="btn btn-danger"><i class='fas'>&#xf2ed; Delete</i></a>
            </td>
        </tr>
    }
</table>

@if (TempData["Remain"] != null)
{
    <div class="card text-center">
        <strong>Remain Amount Is :</strong>@TempData["Remain"]
    </div>
}

MVC_Project/Views/ExCategory/ListExpense.cshtml
@model IEnumerable<MVC_Project.Models.ViewModel>

@{
    ViewBag.Title = "ListExpense";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListExpense</h2>


<script src="~/Scripts/main.js"></script>
<script src="~/Scripts/Fontawsome.js"></script>


@if (TempData["AlertMsg"] != null)
{
    <div class="alert alert-success">
        <strong>Success !!&#9989;</strong>@TempData["AlertMsg"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

<table class="table table-bordered">
    <tr  class="text-capitalize bg-dark text-white text-center">
        <th>Title</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Category Name</th>
        <th>Date</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>@item.expense.Title</td>
            <td>@item.expense.Description</td>
            <td>@item.expense.Amount</td>
            <td>@item.exCategory.Name</td>
            <td>@item.expense.Date</td>
            <td>
                <a href="@Url.Action("EditExpense", new { item.expense.Exp_Id, item.expense.Title, item.expense.Description, item.expense.Amount, item.exCategory.Name, item.expense.Date })" class="btn btn-success"><i class="fas">&#xf044; Edit</i></a>
                <a href="@Url.Action("DeleteEx", new { @item.expense.Exp_Id })" class="btn btn-danger"><i class='fas'>&#xf2ed; Delete</i></a>
            </td>
        </tr>

    }
</table>

MVC_Project/Views/ExCategory/ListLimit.cshtml
@model List<MVC_Project.Models.totalLimit>

@{
    ViewBag.Title = "ListLimit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Icon.js"></script>
<script src="~/Scripts/Fontawsome.js"></script>

<h2>List-Limit</h2>

@if (TempData["AlertMsg"] != null)
{
    <div class="alert alert-success">
        <strong>Success &#9989;</strong>@TempData["AlertMsg"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

@if (TempData["Alertd"] != null)
{
    <div class="alert alert-danger">
        <i style='font-size:24px' class='fas'>&#xf071;</i>@TempData["Alertd"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}

<table class="table table-bordered">
    <tr class="text-capitalize bg-dark text-white text-center">
        <th>Total Limit</th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>@item.Total_Limit</td>
            <td>
                <a href="@Url.Action("EditLimit",new { item.Id,item.Total_Limit })" class="btn btn-success"><i class="fas">&#xf044; Edit</i></a>
            </td>
        </tr>
    }
</table>